### ISSUE TITLE
Small optimization of Ubic::Service::Utils::wait_for_status to prevent last sleep

### ISSUE THREAD

**Issue by Logioniz** [berekuk/Ubic#76]
May be need to prevent last sleep in loop to add simple this line
```perl
last if $trial == $trials;
```
after line 76:
https://github.com/berekuk/Ubic/blob/master/lib/Ubic/Service/Utils.pm#L76

**Comment by berekuk** [comment]
Thanks! Merged and released under 1.58_01.
