### ISSUE TITLE
Version of package is 1.54-1 but current version is 1.60

### ISSUE THREAD

**Issue by and-hom** [berekuk/Ubic#82]
I've cloned git repository (branch master)
Then run `dzil build && cd Ubic* && cp -r ../debian . && debuild`
**Expected:** ubic_1.60\* files are in project directory
**Actual:** ubic_1.54-1\* files are in project directory

Changelog does not contain any new entries since 1.54-1, but file Changes is present. So, I can not reproduce correct deb package without source modifications

**Comment by berekuk** [comment]
That's correct, you'll have to update debian/changelog yourself.
